# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# see: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------
#security.user.name=user # login username
#security.user.password=changeme
#security.user.role=USER # role assigned to the user
security:
  require-ssl: true
  enable-csrf: true
  basic.enabled: false

# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
management:
  security:
    enabled: false
    role: ADMIN
  contextPath: /manage

# ----------------------------------------
# Hystrix, Ribbon & Feign timeout
# ----------------------------------------
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000

feign:
  hystrix:
    enabled: true

# ----------------------------------------
# CUSTOM --- Woofer
# ----------------------------------------
custom:
  rememberMe:
    key: woofer
    param: rememberMe
  access_log:
    config: logback-access.xml
  logging:
    principal:
      hash_algo: none
